<a href="https://colab.research.google.com/github/PaulTitto/Complete-Machine-Learning-Data-Science-Bootcamp-2022/blob/main/introductio_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

## Datatypes & Attribute

In [2]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2.0, 3.3], 
                [3, 5, 6.5]])

a3 = np.array([[[1, 2, 3], 
                [3, 5, 6],
                [7, 8, 9]],
              [[10, 11, 12],
               [13, 14, 15],
               [16, 17, 18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [3. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 3,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [12]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [13]:
type(a1), type(a2), type(a3) 

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [14]:
# Create a Dataframe from a numpy array
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  3.0  5.0  6.5

## CREATING ARRAYS

In [15]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [16]:
sample_array.dtype

dtype('int64')

In [17]:
ones = np.ones((2, 3))

In [18]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
ones.dtype

dtype('float64')

In [20]:
type(ones)

numpy.ndarray

In [21]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [23]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[3, 9, 5, 6, 9],
       [6, 2, 4, 4, 6],
       [9, 0, 7, 6, 8]])

In [24]:
random_array.size

15

In [25]:
random_array.shape

(3, 5)

In [26]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.52467649, 0.46167143, 0.78092332],
       [0.32025059, 0.58195636, 0.06337211],
       [0.14653056, 0.50391163, 0.15141975],
       [0.82168329, 0.89756695, 0.45480694],
       [0.19075672, 0.26142633, 0.84297191]])

In [27]:
random_array_2.shape

(5, 3)

In [28]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.17268156, 0.93118273, 0.5406777 ],
       [0.22550456, 0.2767771 , 0.69099683],
       [0.25982033, 0.88038157, 0.95401612],
       [0.94562848, 0.6748879 , 0.02035954],
       [0.11346355, 0.26738588, 0.30232494]])

In [29]:
# Pseudo-random numbers
np.random.seed(seed=99999)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

In [30]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [31]:
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])

In [32]:
random_array_4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

## 3. Viewing arrays and matrices

In [33]:
np.unique(random_array_4)

array([0, 1, 3, 4, 5, 6, 8, 9])

In [34]:
a1

array([1, 2, 3])

In [35]:
a2

array([[1. , 2. , 3.3],
       [3. , 5. , 6.5]])

In [36]:
a3

array([[[ 1,  2,  3],
        [ 3,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [37]:
a2[1]

array([3. , 5. , 6.5])

In [38]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 3,  5]],

       [[10, 11],
        [13, 14]]])

In [39]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[6, 7, 7, 9, 3],
         [0, 7, 7, 7, 0],
         [5, 4, 3, 1, 3],
         [1, 3, 4, 3, 1]],

        [[9, 5, 9, 1, 2],
         [3, 2, 2, 5, 7],
         [3, 0, 9, 9, 3],
         [4, 5, 3, 0, 4]],

        [[8, 6, 7, 2, 7],
         [3, 8, 6, 6, 5],
         [6, 5, 7, 1, 5],
         [4, 4, 9, 9, 0]]],


       [[[6, 2, 6, 8, 2],
         [4, 1, 6, 1, 5],
         [1, 6, 9, 8, 6],
         [5, 9, 7, 5, 4]],

        [[9, 6, 8, 1, 5],
         [5, 8, 3, 7, 7],
         [9, 4, 7, 5, 9],
         [6, 2, 0, 5, 3]],

        [[0, 5, 7, 1, 8],
         [4, 9, 0, 2, 0],
         [7, 6, 2, 9, 9],
         [5, 1, 0, 0, 9]]]])

In [40]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [41]:
a4[:, :, :, :3]

array([[[[6, 7, 7],
         [0, 7, 7],
         [5, 4, 3],
         [1, 3, 4]],

        [[9, 5, 9],
         [3, 2, 2],
         [3, 0, 9],
         [4, 5, 3]],

        [[8, 6, 7],
         [3, 8, 6],
         [6, 5, 7],
         [4, 4, 9]]],


       [[[6, 2, 6],
         [4, 1, 6],
         [1, 6, 9],
         [5, 9, 7]],

        [[9, 6, 8],
         [5, 8, 3],
         [9, 4, 7],
         [6, 2, 0]],

        [[0, 5, 7],
         [4, 9, 0],
         [7, 6, 2],
         [5, 1, 0]]]])

## 5. MANIPULATING & COMPARING ARRAY

In [43]:
a1

array([1, 2, 3])

In [45]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [46]:
a1 + ones

array([2., 3., 4.])

In [48]:
a1 - ones

array([0., 1., 2.])

In [49]:
a1 * ones

array([1., 2., 3.])

In [50]:
a1

array([1, 2, 3])

In [51]:
a2

array([[1. , 2. , 3.3],
       [3. , 5. , 6.5]])

In [52]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 3. , 10. , 19.5]])

In [53]:
a3

array([[[ 1,  2,  3],
        [ 3,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [54]:
# How can you reshape a2 to be compatible  with a3?
# Search how to reshape arrray numpy
a2 * a3

ValueError: ignored

In [55]:
a1 / ones

array([1., 2., 3.])

In [56]:
a2 / a1

array([[1.        , 1.        , 1.1       ],
       [3.        , 2.5       , 2.16666667]])

In [57]:
a2 // a1

array([[1., 1., 1.],
       [3., 2., 2.]])

In [58]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [ 9.  , 25.  , 42.25]])

In [59]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [ 9.  , 25.  , 42.25]])

In [60]:
np.add(a1, ones)

array([2., 3., 4.])

In [61]:
a1 % 2

array([1, 0, 1])

In [62]:
a1 / 2

array([0.5, 1. , 1.5])

In [63]:
a2 % 2

array([[1. , 0. , 1.3],
       [1. , 1. , 0.5]])

In [67]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [65]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])