<a href="https://colab.research.google.com/github/PaulTitto/Complete-Machine-Learning-Data-Science-Bootcamp-2022/blob/main/introductio_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

## Datatypes & Attribute

In [5]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [6]:
type(a1)

numpy.ndarray

In [7]:
a2 = np.array([[1, 2.0, 3.3], 
                [3, 5, 6.5]])

a3 = np.array([[[1, 2, 3], 
                [3, 5, 6],
                [7, 8, 9]],
              [[10, 11, 12],
               [13, 14, 15],
               [16, 17, 18]]])

In [8]:
a2

array([[1. , 2. , 3.3],
       [3. , 5. , 6.5]])

In [9]:
a3

array([[[ 1,  2,  3],
        [ 3,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [10]:
a1.shape

(3,)

In [11]:
a2.shape

(2, 3)

In [12]:
a3.shape

(2, 3, 3)

In [13]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [14]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [15]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [17]:
type(a1), type(a2), type(a3) 

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [18]:
# Create a Dataframe from a numpy array
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  3.0  5.0  6.5

## CREATING ARRAYS

In [19]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [20]:
sample_array.dtype

dtype('int64')

In [21]:
ones = np.ones((2, 3))

In [22]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
ones.dtype

dtype('float64')

In [24]:
type(ones)

numpy.ndarray

In [25]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [27]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[5, 0, 5, 2, 8],
       [0, 1, 7, 1, 2],
       [8, 0, 2, 7, 7]])

In [28]:
random_array.size

15

In [29]:
random_array.shape

(3, 5)

In [30]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.68019921, 0.61042878, 0.59578855],
       [0.43648399, 0.21941887, 0.99924576],
       [0.75420109, 0.15034151, 0.41766824],
       [0.79600673, 0.42431968, 0.45242633],
       [0.56451341, 0.3829577 , 0.14135468]])

In [31]:
random_array_2.shape

(5, 3)

In [32]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.74693213, 0.22567421, 0.84806222],
       [0.64103677, 0.31756985, 0.76757362],
       [0.50245493, 0.1974325 , 0.64497629],
       [0.50376897, 0.1792106 , 0.15675854],
       [0.50214954, 0.27256578, 0.64512406]])

In [33]:
# Pseudo-random numbers
np.random.seed(seed=99999)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

In [34]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [35]:
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])

In [36]:
random_array_4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

## 3. Viewing arrays and matrices

In [37]:
np.unique(random_array_4)

array([0, 1, 3, 4, 5, 6, 8, 9])

In [38]:
a1

array([1, 2, 3])

In [39]:
a2

array([[1. , 2. , 3.3],
       [3. , 5. , 6.5]])

In [40]:
a3

array([[[ 1,  2,  3],
        [ 3,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [41]:
a2[1]

array([3. , 5. , 6.5])

In [43]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 3,  5]],

       [[10, 11],
        [13, 14]]])

In [44]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[6, 7, 7, 9, 3],
         [0, 7, 7, 7, 0],
         [5, 4, 3, 1, 3],
         [1, 3, 4, 3, 1]],

        [[9, 5, 9, 1, 2],
         [3, 2, 2, 5, 7],
         [3, 0, 9, 9, 3],
         [4, 5, 3, 0, 4]],

        [[8, 6, 7, 2, 7],
         [3, 8, 6, 6, 5],
         [6, 5, 7, 1, 5],
         [4, 4, 9, 9, 0]]],


       [[[6, 2, 6, 8, 2],
         [4, 1, 6, 1, 5],
         [1, 6, 9, 8, 6],
         [5, 9, 7, 5, 4]],

        [[9, 6, 8, 1, 5],
         [5, 8, 3, 7, 7],
         [9, 4, 7, 5, 9],
         [6, 2, 0, 5, 3]],

        [[0, 5, 7, 1, 8],
         [4, 9, 0, 2, 0],
         [7, 6, 2, 9, 9],
         [5, 1, 0, 0, 9]]]])

In [46]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [48]:
a4[:, :, :, :3]

array([[[[6, 7, 7],
         [0, 7, 7],
         [5, 4, 3],
         [1, 3, 4]],

        [[9, 5, 9],
         [3, 2, 2],
         [3, 0, 9],
         [4, 5, 3]],

        [[8, 6, 7],
         [3, 8, 6],
         [6, 5, 7],
         [4, 4, 9]]],


       [[[6, 2, 6],
         [4, 1, 6],
         [1, 6, 9],
         [5, 9, 7]],

        [[9, 6, 8],
         [5, 8, 3],
         [9, 4, 7],
         [6, 2, 0]],

        [[0, 5, 7],
         [4, 9, 0],
         [7, 6, 2],
         [5, 1, 0]]]])