In [10]:
import tensorflow as tf

Matrix multiplication

In machine Learning, Matrix multipilaction is one of the most common tensor operations

There are two rules our tensor

1. The inner dimensions must match
2. The resulting matrix has the shape of Outher dimensions
> http://matrixmultiplication.xyz/

In [11]:
# You can add values to a tensor using the addition operators
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [12]:
# Matrix Multiplication in tensorflow
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [13]:
# Matrix multiplication with Pythin operatro "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [14]:
tensor.shape

TensorShape([2, 2])

In [7]:
# Create a tensor (3,2) Tensor
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])

# Create another (3,2) Tnesor
Y = tf.constant([[7,8],
                 [9,10],
                 [11,23]])
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 23]], dtype=int32)>)

In [8]:
# Try to Matrix multiply tensor of same shape
# tf.matmul(X,Y)

In [9]:
# Let's change the shape of y
tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 23]], dtype=int32)>

In [14]:
X.shape, tf.reshape(Y, shape=(3, 2)).shape

In [15]:
# Try to Matrix multiply X by reshaped Y
X @ tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  55],
       [ 61,  68, 119],
       [ 95, 106, 183]], dtype=int32)>

In [16]:
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  55],
       [ 61,  68, 119],
       [ 95, 106, 183]], dtype=int32)>

In [17]:
tf.reshape(X, shape=(2,3)).shape, Y.shape

(TensorShape([2, 3]), TensorShape([3, 2]))

In [18]:
# can do the same with transopose
X, tf.transpose(X), tf.reshape(X, shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [19]:
# Try matrix mu;tip;aication with transpose rather thean reshape
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89, 153],
       [116, 194]], dtype=int32)>

📖 Resource: Info and example of matrix multiplication: https://www.mathsisfun.com/algebra/matrix-multiplying.html